[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API, App Store Server Notifications and Advanced Commerce API"
version = "4.2.0"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore", "appstore-server-api", "appstore-receipt", "advanced-commerce"]
edition = "2021"

[dependencies]

# Cryptography
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"]  }
pem-rfc7468 = "1.0.0"
der = { version = "0.7.10", features = ["alloc", "oid"] }
x509-cert = { version = "0.2.5", features = ["std"] }
x509-ocsp = { version = "0.2.1" , optional = true }
const-oid = { version = "0.9.6" }
spki = { version = "0.7.3" }
sha1 = { version = "0.10.6" , features = ["oid"]}
p256 = { version = "0.13.2", features = ["ecdsa", "pkcs8"] }
p384 = { version = "0.13.1", features = ["ecdsa"] }
ecdsa = { version = "0.16.9", features = ["signing", "verifying", "der"] }
rsa = "0.9.10"
sha2 = "0.10.9"
signature = "2.2.0"

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149" }
serde_with = { version = "3.16.1", features = ["chrono"] }
serde_repr = "0.1.20"
uuid = { version = "1.20.0", features = ["serde", "v4"] }
chrono = { version = "0.4.43", features = ["serde"] }
base64 = "0.22.1"

# Networking
reqwest = { version = "0.13.1", default-features = false, features = ["json", "http2"], optional = true }
http = { version = "1.4.0", optional = true }

# Utils
thiserror = "2.0.18"

# Tools
regex = { version = "1.12.3", optional = true }

[dev-dependencies]

tokio = { version = "1.49.0", features = ["test-util", "macros"] }
jsonwebtoken = { version = "10.3.0", features = ["use_pem"] }

[features]
api-client = ["dep:http"]
api-client-reqwest = ["api-client", "dep:reqwest"]
api-client-reqwest-native-tls = ["api-client", "dep:reqwest", "reqwest/native-tls"]
receipt-utility = ["dep:regex"]
ocsp = ["dep:x509-ocsp", "dep:reqwest", "reqwest/blocking"]

[[test]]
name = "ass_api_client"
path = "tests/ass_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "ac_api_client"
path = "tests/ac_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "rm_api_client"
path = "tests/rm_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "chain_verifier_ocsp"
path = "tests/chain_verifier_ocsp.rs"
required-features = ["ocsp"]