[package]
name = "app-store-server-library"
description = "The Rust server library for the App Store Server API, App Store Server Notifications and Advanced Commerce API"
version = "5.0.0-alpha.1"
repository = "https://github.com/namecare/app-store-server-library-rust"
homepage = "https://github.com/namecare/app-store-server-library-rust"
authors = ["tkhp", "namecare"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/app-store-server-library"
keywords = ["apple", "appstore", "appstore-server-api", "appstore-receipt", "advanced-commerce"]
edition = "2021"

[dependencies]

# Cryptography - RustCrypto backend (optional)
p256 = { version = "0.14.0", features = ["ecdsa", "pkcs8"], optional = true }
p384 = { version = "0.14.0", features = ["ecdsa"], optional = true }
rsa = { version = "0.10.0-rc.18", optional = true }
sha2 = { version = "0.11.0"}
pem-rfc7468 = {  version = "1.0.0", optional = true }
der = { version = "0.8.1", features = ["alloc", "oid"], optional = true }
x509-cert = { version = "0.3.0", features = ["std"], optional = true }
x509-ocsp = { version = "0.2.1", optional = true, features = ["builder"] }
const-oid = { version = "0.10.2", optional = true }
spki = { version = "0.8.0", optional = true }
sha1 = { version = "0.11.0", features = ["oid"], optional = true }
signature = { version = "3.0.0", optional = true }

# Cryptography - AWS-LC backend (optional)
aws-lc-rs = { version = "1.17.3", optional = true }
aws-lc-sys = { version = "0.43.0", optional = true }

# Serialization
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
serde_with = { version = "3.21.0", features = ["chrono"] }
serde_repr = "0.1.21"
uuid = { version = "1.24.0", features = ["serde", "v4"] }
chrono = { version = "0.4.45", features = ["serde"] }
base64 = "0.22.1"
jsonwebtoken = { version = "10.4.0" }

# Networking
reqwest = { version = "0.13.4", default-features = false, features = ["json", "http2"], optional = true }
http = { version = "1.4.2", optional = true }

# Utils
thiserror = "2.0.19"

# Tools
regex = { version = "1.13.1", optional = true }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["test-util", "macros"] }
jsonwebtoken = { version = "10.4.0", features = ["use_pem"] }

[features]
default = ["rust_crypto"]

rust_crypto = ["dep:pem-rfc7468", "dep:p256", "dep:p384", "dep:rsa", "dep:der", "dep:x509-cert", "dep:const-oid", "dep:spki", "dep:sha1", "dep:signature", "jsonwebtoken/rust_crypto"]
aws_lc = ["dep:aws-lc-rs", "dep:aws-lc-sys", "jsonwebtoken/aws_lc_rs"]

api-client = ["dep:http"]
api-client-reqwest = ["api-client", "dep:reqwest"]
api-client-reqwest-native-tls = ["api-client", "dep:reqwest", "reqwest/native-tls"]
receipt-utility = ["dep:regex"]
ocsp = ["dep:x509-ocsp", "dep:reqwest", "reqwest/blocking", "dep:der", "dep:x509-cert", "dep:const-oid", "dep:sha1"]

[[test]]
name = "ass_api_client"
path = "tests/ass_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "ac_api_client"
path = "tests/ac_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "rm_api_client"
path = "tests/rm_api_client.rs"
required-features = ["api-client"]

[[test]]
name = "chain_verifier_ocsp"
path = "tests/chain_verifier_ocsp.rs"
required-features = ["ocsp"]