#!/usr/bin/env python3

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(HERE, "results", "raw")
OUT_PATH = os.path.join(HERE, "RESULTS.md")

CASES = [
    "verify_notification",
    "verify_transaction",
    "verify_renewal_info",
    "receipt_app",
    "receipt_app_legacy",
    "sign_promotional_offer",
]

BACKEND_ORDER = ["aws_lc", "rust_crypto", "ring"]
BACKEND_LABEL = {
    "aws_lc": "aws-lc-rs",
    "rust_crypto": "RustCrypto",
    "ring": "ring",
}

# receipt parsing touches no crypto, so these rows are expected to match across
# every column; they are kept so both suites run one case list.
NO_CRYPTO = {"receipt_app", "receipt_app_legacy"}


def parse_duration(cell: str) -> float | None:
    parts = cell.split()
    if len(parts) != 2:
        return None
    try:
        value = float(parts[0])
    except ValueError:
        return None
    scale = {"ns": 1.0, "µs": 1e3, "us": 1e3, "ms": 1e6, "s": 1e9}.get(parts[1])
    return value * scale if scale else None


def parse_divan(path: str) -> dict[str, float]:
    """Divan's console table: name and `fastest` share field 0, so median is at index 2."""
    out: dict[str, float] = {}
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if "│" not in line:
                continue
            columns = [c.strip() for c in line.split("│")]
            if len(columns) < 6:
                continue
            head = columns[0].lstrip("├╰│─ ").strip()
            name = re.split(r"\s{2,}", head)[0].strip()
            if name not in CASES:
                continue
            ns = parse_duration(columns[2])
            if ns is not None:
                out[name] = ns
    return out


def read_results() -> dict[str, dict[str, float]]:
    timings: dict[str, dict[str, float]] = {}
    if not os.path.isdir(RAW_DIR):
        print(f"warning: no {RAW_DIR}; run ./run.sh first", file=sys.stderr)
        return timings
    for backend in BACKEND_ORDER:
        path = os.path.join(RAW_DIR, f"{backend}.txt")
        if not os.path.exists(path):
            continue
        try:
            parsed = parse_divan(path)
        except Exception as e:  # noqa: BLE001
            print(f"warning: could not parse {backend}.txt: {e}", file=sys.stderr)
            continue
        if parsed:
            timings[backend] = parsed
    return timings


def read_skipped() -> list[str]:
    path = os.path.join(RAW_DIR, "skipped.txt")
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as fh:
        return [ln.strip() for ln in fh if ln.strip()]


def format_ns(ns: float) -> str:
    if ns < 1_000:
        return f"{ns:.1f} ns"
    if ns < 1_000_000:
        return f"{ns / 1_000:.2f} µs"
    return f"{ns / 1_000_000:.2f} ms"


def build_table(timings) -> tuple[list[str], list[str]]:
    backends = [b for b in BACKEND_ORDER if b in timings]
    header = ["Case"] + [BACKEND_LABEL.get(b, b) for b in backends]
    align = ["---"] + ["---:"] * len(backends)
    lines = ["| " + " | ".join(header) + " |",
             "| " + " | ".join(align) + " |"]
    for case in CASES:
        cells = [f"`{case}`"]
        for b in backends:
            ns = timings.get(b, {}).get(case)
            cells.append("n/a" if ns is None else format_ns(ns))
        lines.append("| " + " | ".join(cells) + " |")
    return lines, backends


def main() -> int:
    timings = read_results()
    skipped = read_skipped()
    table, backends = build_table(timings)

    doc: list[str] = []
    doc.append("# Crypto backend comparison results")
    doc.append("")
    doc.append("Generated by `bench/compare/backend/run.sh`. Regenerate with `./run.sh`, "
               "or re-render existing results with `python3 render.py`.")
    doc.append("")
    doc.extend(table)
    doc.append("")
    doc.append(f"`{'`, `'.join(sorted(NO_CRYPTO))}` touch no crypto; "
               "those rows are expected to agree across every column.")
    doc.append("")
    doc.append("## Coverage")
    doc.append("")
    if skipped:
        doc.append("These backends did not contribute to the table:")
        doc.append("")
        for entry in skipped:
            doc.append(f"- {entry}")
    else:
        doc.append("Skipped or failed backends: none. Every backend ran.")
    doc.append("")
    ran = ", ".join(BACKEND_LABEL.get(b, b) for b in backends) if backends else "none"
    doc.append(f"Backends that reported results: {ran}.")
    doc.append("")

    text = "\n".join(doc)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
